model_list:
  - model_name: qwen3:8b
    litellm_params:
      model: ollama/qwen3:8b
      api_base: http://host.docker.internal:11434
      apiKey: "ollama"
    model_info:
  - model_name: qwen3:32b-q4_K_M
    litellm_params:
      model: ollama/qwen3:32b-q4_K_M
      api_base: http://host.docker.internal:11434
      apiKey: "ollama"
    model_info:


litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]